name: learn repo state between jobs
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: ls  # Nothing
      - uses: actions/checkout@v3
      - run: ls  # some files

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: ls  # nothing again
      - uses: actions/checkout@v3
      - run: ls  # files present