name: learn defaults
description: foo
author: foo
branding:
  icon: moon
  color: gray-dark

inputs:
  foo:
    description: foo
    required: true
    type: boolean


## Also learn using `defaults`.
## ref: https://github.com/orgs/community/discussions/46670 .
## Conclusion (aug 24, 2023): cant use `defaults`, all steps in `steps` need `shell: bash` manually.


## failed
# runs:
#   using: 'composite'
#   steps:
#     - run: echo "hi from myaction/action.yml"



## works fine
runs:
  using: 'composite'
  steps:
    - run: echo "hi from myaction/action.yml"
      shell: bash



## failed
# defaults:
#   run:
#     shell: bash
# runs:
#   using: 'composite'
#   steps:
#     - run: echo "hi from myaction/action.yml"



## failed
# runs:
#   defaults:
#     run:
#       shell: bash
#   using: 'composite'
#   steps:
#     - run: echo "hi from myaction/action.yml"



## failed
# runs:
#   using: 'composite'
#   steps:
#     defaults:
#       run:
#         shell: bash
#     - run: echo "hi from myaction/action.yml"