name: learn defaults
description: foo
author: foo
branding:
  icon: moon
  color: gray-dark

inputs:
  foo:
    description: foo
    required: true
    type: boolean


## Also learn using `defaults`


## failed
# runs:
#   using: 'composite'
#   steps:
#     - run: echo "hi from myaction/action.yml"



## works fine
# runs:
#   using: 'composite'
#   steps:
#     - run: echo "hi from myaction/action.yml"
#       shell: bash



## 
defaults:
  run:
    shell: bash
runs:
  using: 'composite'
  steps:
    - run: echo "hi from myaction/action.yml"