name: learn reusable workflow importing

on: push

jobs:
  run:
    
    ## This one failed.
    ## Ref: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
    # uses: ./.github/foo.yml

    ## works fine
    uses: ./.github/workflows/foo.yml

    ## failed
    # uses: ./.github/myaction/foo.yml

    ## failed
    # uses: ./.github/workflows/abcd/foo.yml



## learning ref: https://stackoverflow.com/questions/73026597/github-actions-suddenly-throwing-no-version-specified-for-reusable-workflows-t