## Manual pull is somehow needed when performing a GitHub
## Actions checkout in multiple jobs. If not pulled,
## the repository will not be updated.

## note: tried this out while writing a blog (nvfp.github.io) about
##       needing to manually pull for GitHub Actions checkout with multiple jobs.

name: manual pull required for actions checkout

on:
  push:
    branches:
      - main

jobs:
  modify-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For committing
    steps:
      - run: |
          echo "::group::ls $(pwd)"
          ls
          echo "::endgroup::"
      - uses: actions/checkout@v3
      - run: |
          echo "::group::ls $(pwd)"
          ls
          echo "::endgroup::"

          echo $(date +"%T") > foo.txt

          echo "::group::ls $(pwd)"
          ls
          echo "::endgroup::"

          ## INTERNAL
          git config user.name "testing"
          git config user.email "b6dbdde63@efa3a3311"
          git add .
          git commit -m "testing..."
          git push
      # - uses: scapeville/action-git-add-all-then-commit-then-push@v1  # EXTERNAL
  checkout-again:
    needs: modify-and-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "::group::ls $(pwd)"
          ls
          echo "::endgroup::"

          echo "::group::git log I"
          git log
          echo "::endgroup::"

          echo "::group::Manual pull"
          git pull
          echo "::endgroup::"

          echo "::group::git log II"
          git log
          echo "::endgroup::"