name: learn reusable workflow importing

on: push

jobs:
  run:
    
    ## This one failed.
    ## Ref: https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
    # uses: ./.github/foo.yml

    ## 
    uses: ./.github/workflows/foo.yml