name: PyCICD init

on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: default branch name
        default: main
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: scapeville/action-PyCICD/init@main
        with:
          BRANCH: ${{ inputs.BRANCH }}