name: test action-create-PR

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # this one is the one that's working
      pull-requests: write  # update: This one is also needed; 'contents' for pushing the branch, and 'this' for making PR.
    steps:
      - uses: actions/checkout@v3
      - run: echo $(date +'%Y%m%d_%H%M%S') > foo123123.txt
      - uses: scapeville/action-create-PR@main
        # with:
        #   git_name: 
        #   git_email: 
        #   PR_title: 
        env:
          GH_TOKEN: ${{ github.token }}


          