name: test action-create-PR

on:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      # contents: write  # dev-docs: gives error: pull request create failed: GraphQL: Resource not accessible by integration (createPullRequest)
      # pull-requests: write  # update: this one didnt work
      contents: write  # this one is the one that's working
      pull-requests: write  # update: This one is also needed; 'contents' for pushing the branch, and 'this' for making PR.
      # checks: write  # still cant create the PR
      
      ## dev-docs: To create a PR, we need the following permissions: 'contents: write', 
      ##           'pull-requests: write'. Plus, manually check the checkbox 'Allow GitHub 
      ##           Actions to create and approve pull requests' at https://github.com/OWNER/REPO/settings/actions.
      
      # pull-requests: read write  # invalid
    steps:
      - uses: actions/checkout@v3
      # - run: git branch

      ## dev-docs: We don't have to explicitly tell users to 'create a branch first then make the changes', we can handle that for them.
      # - uses: scapeville/action-create-PR/makebranch@main
      #   with:
      #     name: foo
      
      # - run: git branch

      - run: echo $(date +'%Y%m%d_%H%M%S') > foo123123.txt

      - uses: scapeville/action-create-PR@main
        with:
          # name: foo  # dev-docs: Initially, this was for the branch name, but it will be autogenerated.
          # title: foo  # dev-docs: initially, this was for 
          git_name: testing action-create-PR
          git_email: nicho@scapeville.com
        env:
          GH_TOKEN: ${{ github.token }}

      # - run: git branch



      